version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd LF2
      - zip -r9 ../LF2deployment_package.zip .
      - cd ..
      - zip -g LF2deployment_package.zip LF2/lambda_function.py
      - cd index-photos
      - zip -r9 ../IndexPhotosdeployment_package.zip .
      - cd ..
      - zip -g IndexPhotosdeployment_package.zip index-photos/lambda_function.py