version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "Updating lambda Function..."
      - cd LF2
      - aws lambda update-function-code --function-name LF2 --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
    